eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8082
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/jorden2014/config_demo #git地址
          uri: https://gitlab.0easy.com/java/cloud-config-repo.git
          username: jorden
          password: Yds15211818173
          search-paths: aiotcloud
      label: master